export enum TrainerType {
  HighIntensityTraining = 'High Intensity Training',
  Yoga = 'Yoga',
  Fitness = 'Fitness',
  Powerlifting = 'Powerlifting',
  Calisthenic = 'Calisthenic',
  Spin = 'Spin',
  Barre = 'Barre',
  Pilates = 'Pilates',
  Bootcamp = 'Bootcamp',
  RockClimbing = 'Rock climbing',
  Other = 'Other',
}

export const TrainerTypeList: string[] = [
  'High Intensity Training',
  'Yoga',
  'Fitness',
  'Powerlifting',
  'Calisthenic',
  'Spin',
  'Barre',
  'Pilates',
  'Bootcamp',
  'Rock climbing',
  'Other',
];

export const TrainerExperienceData: string[] = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '+20',
];
